### ISSUE TITLE
hyprpm add fails

### ISSUE THREAD

**Issue by tuxx** [outfoxxed/hy3#109]
```
$ hyprpm add -v https://github.com/outfoxxed/hy3
[v] version returned: Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


[v] parsed commit cba1ade848feac44b2eda677503900639581c3f4 at branch  on Sat May 4 15:42:32 2024, commits 4606
✔ adding a new plugin repository from https://github.com/outfoxxed/hy3
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 → Cloning https://github.com/outfoxxed/hy3
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
 → hy3 by outfoxxed version
 → Manifest has 9 pins, checking
✔ commit pin 584a1b1e357412a1a4ac40dbc6c4e5adaa7ec59b matched hl, resetting
✔ Hyprland headers OK
 → Building hy3
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/tuxx && PKG_CONFIG_PATH="/home/tuxx/.local/share/hyprpm/headersRoot/share/pkgconfig" cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build
-- The C compiler identification is GNU 14.1.1
-- The CXX compiler identification is GNU 14.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Checking for modules 'hyprland;pixman-1;libdrm;pango;pangocairo'
--   Found hyprland, version 0.39.1
--   Found pixman-1, version 0.43.4
--   Found libdrm, version 2.4.120
--   Found pango, version 1.52.2
--   Found pangocairo, version 1.52.2
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/tuxx/build

 -> cd /tmp/hyprpm/tuxx && PKG_CONFIG_PATH="/home/tuxx/.local/share/hyprpm/headersRoot/share/pkgconfig" cmake --build build
[ 14%] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
In file included from /home/tuxx/.local/share/hyprpm/headersRoot/include/hyprland/src/config/ConfigManager.hpp:20,
                 from /home/tuxx/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:10,
                 from /tmp/hyprpm/tuxx/src/main.cpp:1:
/home/tuxx/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../desktop/LayerSurface.hpp:7:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
    7 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/hy3.dir/build.make:76: CMakeFiles/hy3.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hy3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2


✖ Plugin hy3 failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

✔ all plugins built
✔ installed repository
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!
 ```

```
$ pacman -Ss hyprland | grep -i installed
extra/hyprland 0.40.0-1 [installed]
extra/hyprwayland-scanner 0.3.6-1 [installed]
```

seems that if i copy the `/usr/include/wlr/types/*.h` to `~/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland/wlr/types/` it does build, but does not work.

**Comment by zoli** [comment]
For me this error was resolved after installing "hyprwayland-scanner" but I see you've installed it.

**Comment by tmilner** [comment]
I've got the same issue here. Same Hyprland and hyprwayland-scanner versions.

**Comment by tuxx** [comment]
> For me this error was resolved after installing "hyprwayland-scanner" but I see you've installed it.

I also saw the closed issue from #107 and tried to install hyprwayland-scanner, but it did not resolve my issue.

**Comment by emanuelserpa** [comment]
This problem looks like something about the ongoing rewrite of wlroots' parts inside hyprland.

I would recommend going to the [v0.39.1](https://github.com/hyprwm/Hyprland/releases/tag/v0.39.1) until these changes settles.

**Comment by LRitzdorf** [comment]
Works on v0.40.0 for me, as of earlier today. Since this looks like a headers issue, it might be worth running `hyprpm update -v` for details, and possibly adding `-f` to force a refresh if no changes are detected automatically?

**Comment by outfoxxed** [comment]
Missing includes in hyprland itself aren't an issue on hy3's end. Those are related to hyprland itself, and should be reported there. If it hasn't been fixed yet (I'm fairly sure it has) please open an issue there.

**Comment by tuxx** [comment]
Thanks for clearing that up @outfoxxed ! Seems if you run `hyprpm update -f` the headers get downloaded and this fixed my issue, i see now that @LRitzdorf also made a comment about this. If anyone else is having this issue just force update hyprpm :heart:
