### ISSUE TITLE
No auto-rerendering on changing Hyprland settings

### ISSUE THREAD

**Issue by postsolar** [outfoxxed/hy3#42]
This happened somewhere between 0.30 release and the current master 2b53cca. It works fine on bare Hyprland but not with hy3. The gist is that whenever I do something to my Hyprland (or Hy3) config I'd need to e.g. switch the focused window in order for the change to be applied, and it's like this for both editing config values manually and using hyprctl.

**Comment by outfoxxed** [comment]
Fixed in f408153

**Comment by postsolar** [comment]
After update + reboot yay is telling me I'm on [f408153](https://github.com/outfoxxed/hy3/commit/f4081531bdc8c9f5a38261867b7107c746db7eee) but it's still the same
