### ISSUE TITLE
Hyprland crash after waking up out of suspend

### ISSUE THREAD

**Issue by zoli** [outfoxxed/hy3#66]
Sometimes after suspend when I want to unlock swaylock hyprland crashes and in the crash report it seems its related to hy3. Here is the backtrace:
```
Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x55f711427412]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x5c5) [0x55f7113f48a5]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x4c) [0x55f71136e5ec]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x79335405c710]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x158200) [0x793354176200]
		??
		??:0
	#5 | /usr/lib/libstdc++.so.6(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_+0xba) [0x79335435969a]
		??
		??:0
	#6 | /home/zoli/.local/share/hyprpm/hy3/hy3.so(_ZN9Hy3Layout24updateAutotileWorkspacesEv+0x5f) [0x79334127e62f]
		??
		??:0
	#7 | /home/zoli/.local/share/hyprpm/hy3/hy3.so(_ZN9Hy3Layout10insertNodeER7Hy3Node+0x2f7) [0x7933412810d7]
		??
		??:0
	#8 | /home/zoli/.local/share/hyprpm/hy3/hy3.so(_ZN9Hy3Layout8onEnableEv+0x79) [0x79334127bbb9]
		??
		??:0
	#9 | Hyprland(_ZN14CConfigManager18loadConfigLoadVarsEv+0x1143) [0x55f7113d37c3]
		??
		??:0
	#10 | Hyprland(_ZN14CConfigManager4tickEv+0x19f) [0x55f7113d461f]
		??
		??:0
	#11 | Hyprland(_ZN14CConfigManager17handlePluginLoadsEv+0x509) [0x55f7113df569]
		??
		??:0
	#12 | Hyprland(_ZN14CConfigManager18loadConfigLoadVarsEv+0x1261) [0x55f7113d38e1]
		??
		??:0
	#13 | Hyprland(_ZN14CConfigManager4tickEv+0x19f) [0x55f7113d461f]
		??
		??:0
	#14 | Hyprland(_Z11handleTimerPv+0x49) [0x55f711463bd9]
		??
		??:0
	#15 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0x2e7) [0x793354967d27]
		??
		??:0
	#16 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7933549682d7]
		??
		??:0
	#17 | Hyprland(_ZN11CCompositor15startCompositorEv+0xc65) [0x55f71136fef5]
		??
		??:0
	#18 | Hyprland(main+0x727) [0x55f7113561f7]
		??
		??:0
	#19 | /usr/lib/libc.so.6(+0x27cd0) [0x793354045cd0]
		??
		??:0
	#20 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x793354045d8a]
		??
		??:0
	#21 | Hyprland(_start+0x25) [0x55f71136b815]
		??
		??:0
```

**Comment by Arjun31415** [comment]
Is it suspend or is it after swaylock ?

**Comment by zoli** [comment]
> Is it suspend or is it after swaylock ?. Does it wake up from suspend successfully ?. If not, and if you have nvidia card then it is a known issue of waking up from suspend (with nvidia)

It is suspend but it wakes up after suspend and I see swaylock background although it doesn't respond to any of my key inputs. I also don't have nvidia card, Its Intel graphics as far as I know.

**Comment by Arjun31415** [comment]
I think it is related to this https://github.com/hyprwm/Hyprland/issues/1728. 
For me it is fixed using the service file mentioned in the thread

**Comment by zoli** [comment]
Thanks, I will test it.

**Comment by ZreXoc** [comment]
anyone finds the solution? I still get the problem
For me I got two monitors and after resume one of them shows a black screen (but is listed with `hyprctl monitors all`)

**Comment by Arjun31415** [comment]
Did u test the solution linked in comments ?

**Comment by ZreXoc** [comment]
> anyone finds the solution? I still get the problem with `options nvidia NVreg_RegistryDwords="OverrideMaxPerf=0x1"` For me I got two monitors and after resume one of them shows a black screen (but is listed in `hyprctl monitors all`)

fix with `https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend`

**Comment by zoli** [comment]
This is fixed for me. Not by the solutions above but I think by updates in Hyprland or hy3.
